### ISSUE TITLE
Reconsider crosslinks between sections

### ISSUE THREAD

**Issue by skyschub** [diaspora/north-star#24]
Currently, all sections have persistent crosslinks in the right header part that direct the readers towards other parts of the site:

![Screen Shot 2020-11-15 at 18 19 56](https://user-images.githubusercontent.com/344777/99191781-3214a900-276f-11eb-95d1-63f0c2b95b39.png)
![Screen Shot 2020-11-15 at 18 16 03](https://user-images.githubusercontent.com/344777/99191745-f7ab0c00-276e-11eb-9bc3-fc7ecd4b103e.png)
![Screen Shot 2020-11-15 at 18 16 07](https://user-images.githubusercontent.com/344777/99191746-f843a280-276e-11eb-81f5-cc62778b54d8.png)
![Screen Shot 2020-11-15 at 18 16 15](https://user-images.githubusercontent.com/344777/99191747-f8dc3900-276e-11eb-9479-71fea299025c.png)

The idea is, in principle, good. However, it takes up a lot of space in the header, and reduces the amount of actual navigation items we can place. Also, in some cases, this already breaks for smaller, but not yet mobile, viewports:

![Screen Shot 2020-11-15 at 18 16 36](https://user-images.githubusercontent.com/344777/99191768-18736180-276f-11eb-8520-5da5f6ce51f9.png)

I like the large CTA button, but maybe we can rethink this a bit to still have some form of crosslinks available, while not eating up the entire header. Maybe a dropdown-thingy?

**Comment by jhass** [comment]
Not a too big fan of dropdowns personally. Maybe we can split it into a sub/super and main header in some way?

```
+-----------------------------------------------------------------------------------------------+
|                                                                                               |
|                                                                                               |
|    LOGO                                                    A     B    C            CTA        |
|                                                                                               |
+-----------------------------------------------------------------------------------------------+
|                                        X       Y       Z                                      |
|                                                                                               |
+-----------------------------------------------------------------------------------------------+

**Comment by skyschub** [comment]
I played around with @jhass idea and came up with a prototype:

![Screen Shot 2020-11-23 at 01 37 22](https://user-images.githubusercontent.com/344777/99921716-8c43da00-2d2c-11eb-86e7-5141dcff3def.png)
![Screen Shot 2020-11-23 at 01 37 31](https://user-images.githubusercontent.com/344777/99921719-8fd76100-2d2c-11eb-964e-c2a37b56dea0.png)
![Screen Shot 2020-11-23 at 01 37 35](https://user-images.githubusercontent.com/344777/99921724-9239bb00-2d2c-11eb-95e5-f7394669536a.png)
![Screen Shot 2020-11-23 at 01 37 39](https://user-images.githubusercontent.com/344777/99921726-949c1500-2d2c-11eb-8a96-399617210929.png)

The cross-links are now always the same, and there always is a link to all sections, even the current one. The Call-to-Action button is the same as before, and puts the reader back towards the project site if they're lost somewhere else. The second navigation line always contains links to contents within the current section.

I noticed that the mockup had the second-line centered, but that looks really odd to me:

![Screen Shot 2020-11-23 at 01 41 13](https://user-images.githubusercontent.com/344777/99921781-fe1c2380-2d2c-11eb-99d1-de3afafb1056.png)

I have yet to implement some "active" states, at least for the crosslinks, as well as a mobile version. But so far, opinions?

**Comment by skyschub** [comment]
Okay, I had to polish it a bit more for me to be comfortable. Also, I felt a bit tired of our permanent gray-on-grey, and because we already have a green CTA button, I went with a bit of green:

![Screen Shot 2020-11-23 at 06 28 46](https://user-images.githubusercontent.com/344777/99931605-73035380-2d55-11eb-95bc-ca2dcb1674cd.png)

This works fine down to 768px screen width, thanks to the awesomeness that is modern CSS:

![Screen Shot 2020-11-23 at 06 28 59](https://user-images.githubusercontent.com/344777/99931638-8f06f500-2d55-11eb-9f5d-15532432c6b1.png)

And below that, it just collapses into a mobile'y view (where the popout is yet to be done):

![Screen Shot 2020-11-23 at 06 29 31](https://user-images.githubusercontent.com/344777/99931664-a47c1f00-2d55-11eb-865b-bca11aba6d9c.png)

---

I feel like that's a good solution to the issue here, and keeps all the crosslinks in view while also clearly indicating what's available in the current section.

**Comment by skyschub** [comment]
I consider this done for now.
