### ISSUE TITLE
Add an "edit this site" link

### ISSUE THREAD

**Issue by skyschub** [diaspora/north-star#3]
This popped up in a chat on 35c3, but I don't remember who said it. 😿 

All contents are markdown files anyway, so we could add a link to GitHub to each site. When on GitHub, the workflow is actually surprisingly simple, clicking the "edit" button automatically creates a fork if you don't have write permissions to the repo, and it's very easy to create a pull request from there.

**Comment by skyschub** [comment]
Styling is still ToDo, but that will be done when #1 is done.

**Comment by SuperTux88** [comment]
> but I don't remember who said it.

By the way, that was me, and thanks for adding it :cookie: :heart:
